
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lk
 */
public class DescripcionProducto extends javax.swing.JFrame {

    /**
     * Creates new form DescripcionProducto
     */
    public DescripcionProducto() {
        initComponents();
        this.cbAgregarTipo.addItem("Plomeria");
        this.cbAgregarTipo.addItem("Hogar");
        this.cbAgregarTipo.addItem("moateriales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDescripcionProducto = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        lbCosto = new javax.swing.JLabel();
        txtAgregarCosto = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        cbAgregarTipo = new javax.swing.JComboBox();
        lbProveedor = new javax.swing.JLabel();
        txtAgregarProveedor = new javax.swing.JTextField();
        lbStock = new javax.swing.JLabel();
        txtAgregarStock = new javax.swing.JTextField();
        lbDescripcion = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtAgregarDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 640));
        setName(""); // NOI18N
        getContentPane().setLayout(null);

        pnDescripcionProducto.setAutoscrolls(true);
        pnDescripcionProducto.setPreferredSize(new java.awt.Dimension(1204, 1204));

        lbNombre.setText("Nombre");
        lbNombre.setName("NOMBRE"); // NOI18N

        txtAgregarNombre.setEnabled(false);
        txtAgregarNombre.setName("nombre"); // NOI18N
        txtAgregarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarNombreKeyTyped(evt);
            }
        });

        lbCosto.setText("Costo");
        lbCosto.setName("COSTO"); // NOI18N

        txtAgregarCosto.setEnabled(false);
        txtAgregarCosto.setName("costo"); // NOI18N
        txtAgregarCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarCostoActionPerformed(evt);
            }
        });
        txtAgregarCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarCostoKeyTyped(evt);
            }
        });

        lbTipo.setText("Tipo");
        lbTipo.setName("TIPO"); // NOI18N

        cbAgregarTipo.setEnabled(false);
        cbAgregarTipo.setName("tipo"); // NOI18N

        lbProveedor.setText("Proveedor");
        lbProveedor.setName("PROVEEDOR"); // NOI18N

        txtAgregarProveedor.setEnabled(false);
        txtAgregarProveedor.setName("proveedor"); // NOI18N
        txtAgregarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarProveedorKeyTyped(evt);
            }
        });

        lbStock.setText("Stock");
        lbStock.setName("STOCK"); // NOI18N

        txtAgregarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAgregarStock.setEnabled(false);
        txtAgregarStock.setName("stock"); // NOI18N
        txtAgregarStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarStockKeyTyped(evt);
            }
        });

        lbDescripcion.setText("Descripcion");
        lbDescripcion.setName("DESCRIPCION"); // NOI18N

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");

        txtAgregarDescripcion.setEnabled(false);
        txtAgregarDescripcion.setName("Descripcion"); // NOI18N
        txtAgregarDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarDescripcionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnDescripcionProductoLayout = new javax.swing.GroupLayout(pnDescripcionProducto);
        pnDescripcionProducto.setLayout(pnDescripcionProductoLayout);
        pnDescripcionProductoLayout.setHorizontalGroup(
            pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDescripcionProductoLayout.createSequentialGroup()
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDescripcionProductoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre)
                            .addComponent(lbCosto)
                            .addComponent(lbTipo)
                            .addComponent(lbProveedor)
                            .addComponent(lbStock)
                            .addComponent(lbDescripcion))
                        .addGap(89, 89, 89)
                        .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAgregarNombre)
                                .addComponent(txtAgregarCosto)
                                .addComponent(cbAgregarTipo, 0, 219, Short.MAX_VALUE)
                                .addComponent(txtAgregarProveedor)
                                .addGroup(pnDescripcionProductoLayout.createSequentialGroup()
                                    .addComponent(txtAgregarStock)
                                    .addGap(106, 106, 106)))
                            .addComponent(txtAgregarDescripcion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDescripcionProductoLayout.createSequentialGroup()
                        .addContainerGap(115, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        pnDescripcionProductoLayout.setVerticalGroup(
            pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDescripcionProductoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCosto)
                    .addComponent(txtAgregarCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(cbAgregarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProveedor)
                    .addComponent(txtAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStock)
                    .addComponent(txtAgregarStock))
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDescripcionProductoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbDescripcion))
                    .addGroup(pnDescripcionProductoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtAgregarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnDescripcionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnAtras))
                .addGap(64, 64, 64))
        );

        lbNombre.getAccessibleContext().setAccessibleName("");
        txtAgregarNombre.getAccessibleContext().setAccessibleName("descripcion");

        getContentPane().add(pnDescripcionProducto);
        pnDescripcionProducto.setBounds(0, 0, 530, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgregarCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarCostoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //Esta validacion lo que hace sencillamente es que al momento de guardar reconocer de manera inmediata que caja de texto esta vacia
        //si es asi entonces presenta una advertencia que debe ser llenada
        Component[] componentes=pnDescripcionProducto.getComponents();
        int i;
        
          for(i=1;i<componentes.length;i++)
          {
              //DEbug
              System.out.print(componentes[i].getName());
              if(componentes[i] instanceof JTextField)
              {
                if(((JTextField)componentes[i]).getText().equals(""))
                {
                 JOptionPane.showMessageDialog(componentes[i],"Espacios en blanco:::"+componentes[i].getName());
                }
              }
          }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        //El diseño anterior ocupaba muchos recursos en cuanto al uso de botones innecesarios haciendo un recorrido al jpane y un cast 
          //validamos n componentes      
        Component[] componentes=pnDescripcionProducto.getComponents();
        int i;
        cbAgregarTipo.setEnabled(true);
        for(i=1;i<componentes.length;i++)
          {
              System.out.print(componentes[i].getName());
              if(componentes[i] instanceof JTextField)
              {
                ((JTextField)componentes[i]).setEnabled(true);
              }
          }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtAgregarNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarNombreKeyTyped
        // TODO add your handling code here:
        String cadena=String.valueOf(evt.getKeyChar());
        if(txtAgregarNombre.getText().length()>=35)
        {
            evt.consume();
        }
        if(!cadena.matches("[A-Z|a-z|\\s]"))
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtAgregarNombreKeyTyped

    private void txtAgregarCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarCostoKeyTyped
        // TODO add your handling code here:
        int c=0;  
        String cadena=String.valueOf(evt.getKeyChar());
        if(txtAgregarCosto.getText().length()>=7)
        {
            evt.consume();
        }
        if(!cadena.matches("[0-9]"))
        {
            
           
             evt.consume(); 
              
        }
        
    }//GEN-LAST:event_txtAgregarCostoKeyTyped

    private void txtAgregarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarProveedorKeyTyped
        // TODO add your handling code here:
         String cadena=String.valueOf(evt.getKeyChar());
        if(txtAgregarProveedor.getText().length()>=35)
        {
            evt.consume();
        }
        if(!cadena.matches("[A-Z|a-z|\\s]"))
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtAgregarProveedorKeyTyped

    private void txtAgregarStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarStockKeyTyped
        // TODO add your handling code here:
           String cadena=String.valueOf(evt.getKeyChar());
        if(txtAgregarStock.getText().length()>=6)
        {
            evt.consume();
        }
        if(!cadena.matches("[0-9]"))
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtAgregarStockKeyTyped

    private void txtAgregarDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarDescripcionKeyTyped
        // TODO add your handling code here:
         String cadena=String.valueOf(evt.getKeyChar());
        if(txtAgregarDescripcion.getText().length()>=150)
        {
            evt.consume();
        }
        if(!cadena.matches("[A-Z|a-z|\\s]"))
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtAgregarDescripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescripcionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescripcionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescripcionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescripcionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DescripcionProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cbAgregarTipo;
    private javax.swing.JLabel lbCosto;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbStock;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JPanel pnDescripcionProducto;
    private javax.swing.JTextField txtAgregarCosto;
    private javax.swing.JTextField txtAgregarDescripcion;
    private javax.swing.JTextField txtAgregarNombre;
    private javax.swing.JTextField txtAgregarProveedor;
    private javax.swing.JTextField txtAgregarStock;
    // End of variables declaration//GEN-END:variables
}
